"""add hot

Revision ID: 113c8fe35e46
Revises: 218a7fb17df1
Create Date: 2020-01-17 11:12:44.130322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113c8fe35e46'
down_revision = '218a7fb17df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa', sa.Column('hot', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa', 'hot')
    # ### end Alembic commands ###
