"""add nlp

Revision ID: 218a7fb17df1
Revises: 87e713151dd4
Create Date: 2020-01-16 14:30:34.717206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218a7fb17df1'
down_revision = '87e713151dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa', sa.Column('nlp_keywords', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa', 'nlp_keywords')
    # ### end Alembic commands ###
