"""update model1

Revision ID: ed9f08135452
Revises: 46e023a4d2a7
Create Date: 2020-01-16 11:42:04.162601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9f08135452'
down_revision = '46e023a4d2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa', 'test')
    # ### end Alembic commands ###
